### Based on [NumPy cheat sheet](http://datacamp-community-prod.s3.amazonaws.com/ba1fe95a-8b70-4d2f-95b0-bc954e9071b0)

In [ ]:
import numpy as np

## Creating arrays

In [ ]:
# Manual array construction
a = np.array([1, 2, 3])
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype=float)
c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]], dtype = float)

In [ ]:
# Placeholder array: zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# Placeholder array: ones
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [ ]:
# Placeholder array: evenly spaced values
np.arange(10, 25, 5)

array([10, 15, 20])

In [ ]:
# Placeholder array: evenly spaced values (alternate)
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [ ]:
# Placeholder array: constant array
np.full((2, 2), 3)

array([[3, 3],
       [3, 3]])

In [ ]:
# Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Placeholder array: random initialization
np.random.random((3, 3))

array([[0.03389399, 0.51503364, 0.481698  ],
       [0.04005319, 0.35013549, 0.01200971],
       [0.87120884, 0.84924196, 0.59093977]])

In [ ]:
# Placeholder array: uninitialized array
np.empty((4, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ],
       [1.25, 1.5 ],
       [1.75, 2.  ]])

## I/O

In [ ]:
# Saving a single array to disk
np.save('a_array', a)

In [ ]:
# Saving multiple arrays to a single file
np.savez('ab_array.npz', a, b)

In [ ]:
# # Loading array from disk
# np.load('a_array.npy')

## Array properties

In [ ]:
# Shape
a.shape

(3,)

In [ ]:
# Length
len(a)

3

In [ ]:
# Number of dimensions
a.ndim

1

In [ ]:
# Number of array elements
b.size

6

In [ ]:
# Data type of array elements
b.dtype

dtype('float64')

In [ ]:
# Name of data type
b.dtype.name

'float64'

In [ ]:
# Convert array to different type
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

## Array math

In [ ]:
# Subtraction
a - b

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [ ]:
# Subtraction (alternate)
np.subtract(a, b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [ ]:
# Addition
a + b

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [ ]:
# Addition (alternate)
np.add(a, b)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [ ]:
# Division
a / b

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [ ]:
# Division (alternate)
np.divide(a, b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [ ]:
# Multiplication
a * b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [ ]:
# Multiplication (alternate)
np.multiply(a, b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [ ]:
# Elementwise matrix-matrix exponentiation 
a ** b

array([[  1.,   4.,  27.],
       [  1.,  32., 729.]])

In [ ]:
# Elementwise scalar-matrix exponentiation
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [ ]:
# Elementwise square root
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
# Elementwise sine
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [ ]:
# Elementwise log
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [ ]:
# Dot product
a.dot(b.T)

array([14.5, 32. ])

In [ ]:
# Elementwise comparison
a == b

array([[False,  True,  True],
       [False, False, False]])

In [ ]:
# Array-wise comparison
np.array_equal(a, b)

False

In [ ]:
# Array-wise sum
a.sum()

6

In [ ]:
# Arary-wise min
a.min()

1

In [ ]:
# Max value of row
b.max(axis=0)

array([4., 5., 6.])

In [ ]:
# Cumulative sum of elements
b.cumsum(axis=1)

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [ ]:
# Mean
a.mean()

2.0

In [ ]:
# Median
np.median(a)

2.0

In [ ]:
# Correlation coefficient
np.corrcoef(a, b)

array([[1.        , 0.98198051, 1.        ],
       [0.98198051, 1.        , 0.98198051],
       [1.        , 0.98198051, 1.        ]])

In [ ]:
# Standard deviation
np.std(b)

1.5920810978785667

## Copying arrays

In [ ]:
# Create a shallow copy of an array
a_prime = np.copy(a)
a_prime

array([1, 2, 3])

In [ ]:
# Create a deep copy of an array
a_double_prime = a.copy()
a_double_prime

array([1, 2, 3])

## Sorting arrays

In [ ]:
# Sort an array
a.sort()
a

array([1, 2, 3])

In [ ]:
# Sort elements of a given axis
b.sort(axis=0)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

## Subsetting, slicing, indexing

In [ ]:
# Single element access
a[2]

3

In [ ]:
# Row, col indexing
b[0, 2]

3.0

In [ ]:
# Row, col indexing (alternate)
b[0][2]

3.0

In [ ]:
# Slicing
b[0:2, 1]

array([2., 5.])

In [ ]:
# Randomly-initialized 3-tensor
d = np.random.random((2, 2, 2))
d

array([[[0.81767198, 0.10802853],
        [0.64982116, 0.34530318]],

       [[0.31400063, 0.82982114],
        [0.27590405, 0.11571403]]])

In [ ]:
# Lazy slicing
d[1,...]

array([[0.31400063, 0.82982114],
       [0.27590405, 0.11571403]])

In [ ]:
# Lazy slicing (alternate)
d[1,:,:]

array([[0.31400063, 0.82982114],
       [0.27590405, 0.11571403]])

In [ ]:
# Reverse array
a[::-1]

array([3, 2, 1])

In [ ]:
# Boolean indexing
d[d<0.5]

array([0.10802853, 0.34530318, 0.31400063, 0.27590405, 0.11571403])

In [ ]:
# Coordinate indexing
d[[1, 0, 1, 1, 0], [0, 1, 1, 0, 1]] # return elements at (1,0), (0,1), (1,1), (1,0), (0,1)

array([[0.31400063, 0.82982114],
       [0.64982116, 0.34530318],
       [0.27590405, 0.11571403],
       [0.31400063, 0.82982114],
       [0.64982116, 0.34530318]])

## Array manipulation

In [ ]:
# Transpose
np.transpose(b)

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [ ]:
# Transpose (alternate)
b.T

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [ ]:
# Flatten array
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [ ]:
# Reshape (returns new array)
d.reshape(2, 4, 1)

array([[[0.81767198],
        [0.10802853],
        [0.64982116],
        [0.34530318]],

       [[0.31400063],
        [0.82982114],
        [0.27590405],
        [0.11571403]]])

In [ ]:
# Reshape (in place)
d.resize((2,4,1))
d.shape

(2, 4, 1)

In [ ]:
# Insert element in array
np.insert(a, 1, 10)

array([ 1, 10,  2,  3])

In [ ]:
# Delete element from array
np.delete(a, [1])

array([1, 3])

In [ ]:
# Concatenate arrays
x, y = np.random.random((2, 2)), np.random.random((2,2))
np.concatenate((x,y), axis=0)

array([[0.011766  , 0.25435251],
       [0.26627139, 0.8455415 ],
       [0.74123715, 0.05240171],
       [0.81083758, 0.89976786]])

In [ ]:
# Stack arrays vertically
np.vstack((x,y))

array([[0.011766  , 0.25435251],
       [0.26627139, 0.8455415 ],
       [0.74123715, 0.05240171],
       [0.81083758, 0.89976786]])

In [ ]:
# Stack arrays vertically (alternate)
np.r_[x,y]

array([[0.011766  , 0.25435251],
       [0.26627139, 0.8455415 ],
       [0.74123715, 0.05240171],
       [0.81083758, 0.89976786]])

In [ ]:
# Stack arrays horizontally
np.hstack((x,y))

array([[0.011766  , 0.25435251, 0.74123715, 0.05240171],
       [0.26627139, 0.8455415 , 0.81083758, 0.89976786]])

In [ ]:
# Stack arrays horizontally (alternate #1)
np.column_stack((x,y))

array([[0.011766  , 0.25435251, 0.74123715, 0.05240171],
       [0.26627139, 0.8455415 , 0.81083758, 0.89976786]])

In [ ]:
# Stack arrays horizontally (alternate #2)
np.c_[x,y]

array([[0.011766  , 0.25435251, 0.74123715, 0.05240171],
       [0.26627139, 0.8455415 , 0.81083758, 0.89976786]])

In [ ]:
# Split array horizontally at given index
np.hsplit(b, 3)

[array([[1.5],
        [4. ]]), array([[2.],
        [5.]]), array([[3.],
        [6.]])]

In [ ]:
# Split array vertically at given index
np.vsplit(b, 2)

[array([[1.5, 2. , 3. ]]), array([[4., 5., 6.]])]