### Based on [SciPy cheat sheet](http://datacamp-community-prod.s3.amazonaws.com/dfdb6d58-e044-4b38-bab3-5de0b825909b)

In [70]:
from scipy import linalg, special, misc, sparse
import numpy as np

## Matrix operations

In [19]:
# Create a randomly initialized matrix
A = np.matrix(np.random.random((2,2)))

In [20]:
# Create a randomly initialized matrix (alternate)
B = np.mat(np.random.random((10,5)))

In [21]:
# Create a matrix manually
C = np.mat([[1,2], [3,4]])

In [22]:
# Inverse
A.I

matrix([[-0.88942867,  2.11427855],
        [ 1.9479634 , -1.91483897]])

In [23]:
# Inverse (alternate)
linalg.inv(A)

array([[-0.88942867,  2.11427855],
       [ 1.9479634 , -1.91483897]])

In [24]:
# Transpose
A.T

matrix([[0.79275462, 0.80646832],
        [0.87532378, 0.36822871]])

In [25]:
# Conjugate transpose
A.H

matrix([[0.79275462, 0.80646832],
        [0.87532378, 0.36822871]])

In [26]:
# Trace
np.trace(A)

1.1609833249348365

In [27]:
# L2 norm
linalg.norm(A)

1.4766973756460655

In [28]:
# L1 norm
linalg.norm(A, 1)

1.5992229408699021

In [29]:
# L-inf norm
linalg.norm(A, np.inf)

1.668078394622568

In [31]:
# Rank
np.linalg.matrix_rank(C)

2

In [32]:
# Determinant
linalg.det(A)

-0.414005892475872

In [36]:
# Least squares regression
linalg.lstsq(A, C)

(array([[ 5.45340699,  6.67825687],
        [-3.79655351, -3.76342908]]),
 array([], dtype=float64),
 2,
 array([1.44878427, 0.2857609 ]))

In [37]:
# Pseudoinverse (least squares)
linalg.pinv(C)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [38]:
# Pseudoinverse (SVD)
linalg.pinv2(C)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [57]:
# Dot product
np.dot(A, C)

matrix([[3.41872595, 5.08680435],
        [1.91115445, 3.08585148]])

In [58]:
# Inner product
np.inner(A, C)

matrix([[2.54340217, 5.87955896],
        [1.54292574, 3.89231981]])

In [59]:
# Outer product
np.outer(A, C)

array([[0.79275462, 1.58550923, 2.37826385, 3.17101846],
       [0.87532378, 1.75064756, 2.62597134, 3.50129511],
       [0.80646832, 1.61293665, 2.41940497, 3.2258733 ],
       [0.36822871, 0.73645742, 1.10468613, 1.47291483]])

In [60]:
# Tensor dot product
t1 = np.random.random((2, 2, 2))
t2 = np.random.random((2, 2, 2))
np.tensordot(t1, t2)

array([[0.50094249, 1.196836  ],
       [0.18347575, 0.75211667]])

In [61]:
# Kronecker product
np.kron(A, C)

matrix([[0.79275462, 1.58550923, 0.87532378, 1.75064756],
        [2.37826385, 3.17101846, 2.62597134, 3.50129511],
        [0.80646832, 1.61293665, 0.36822871, 0.73645742],
        [2.41940497, 3.2258733 , 1.10468613, 1.47291483]])

In [71]:
# Matrix exponential
linalg.expm(A)

array([[2.92952309, 1.76738542],
       [1.62835787, 2.07235353]])

In [72]:
# Matrix log
linalg.logm(A)

array([[-0.24241656+1.1860443j ,  0.81865502-1.58662919j],
       [ 0.75425729-1.46182044j, -0.63945851+1.95554835j]])

In [73]:
# Matrix sine
linalg.sinm(C)

array([[-0.46558149, -0.14842446],
       [-0.22263669, -0.68821818]])

In [74]:
# Hyperbolic matrix sine
linalg.sinhm(C)

array([[25.4317178 , 37.62006779],
       [56.43010168, 81.86181949]])

In [77]:
# Matrix square root
linalg.sqrtm(A)

array([[0.74879865+0.20193329j, 0.60753588-0.270136j  ],
       [0.55974539-0.24888633j, 0.454148  +0.33294736j]])

In [81]:
# Arbitrary matrix functions
linalg.funm(A, lambda x: x+1)

array([[1.79275462, 0.87532378],
       [0.80646832, 1.36822871]])

In [82]:
# Orthogonal Procrustes
linalg.orthogonal_procrustes(A, C)

(array([[ 0.91533312,  0.4026975 ],
        [-0.4026975 ,  0.91533312]]), 7.031016169830095)

## Sparse matrices

In [40]:
# Identity matrix
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
# Compressed sparse row matrix
sparse.csr_matrix(I)

<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [46]:
# Compressed sparse column matrix
sparse.csc_matrix(I)

<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Column format>

In [48]:
# Dictionary of keys matrix
J = sparse.dok_matrix(A)

In [49]:
# Sparse matrix to dense matrix
J.todense()

matrix([[0.79275462, 0.87532378],
        [0.80646832, 0.36822871]])

## Sparse matrix operations

In [66]:
from scipy.sparse import linalg as sp_linalg

In [68]:
# Inverse
sp_linalg.inv(sparse.csc_matrix(I))

<3x3 sparse matrix of type '<class 'numpy.float64'>'
	with 3 stored elements in Compressed Sparse Column format>

In [69]:
# Norm
sp_linalg.norm(sparse.csc_matrix(I))

1.7320508075688772

## Decompositions

In [84]:
# Eigenvalue decomposition
la, v = linalg.eig(A)

In [85]:
# Unpack eigenvalues
l1, l2 = la

In [86]:
# Access eigenvectors
v[:,0]

array([0.80095069, 0.59873032])

In [87]:
# Unpack eigenvalues
linalg.eigvals(A)

array([ 1.44708064+0.j, -0.28609732+0.j])

In [90]:
# SVD
U, s, Vh = linalg.svd(B)
U.shape, s.shape, Vh.shape, B.shape

((10, 10), (5,), (5, 5), (10, 5))

In [91]:
# Construct sigma matrix associated to SVD
M,N = B.shape
S = linalg.diagsvd(s, M, N)
S

array([[3.76623759, 0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.30250561, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.81053874, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.76253153, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.64255997],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

## Misc operations

In [12]:
# Polynomial creation
p = np.poly1d([1, 2, 3])
p

poly1d([1, 2, 3])

In [13]:
# Vectorize a function
def f(x):
  if x < 0:
    return x**2
  else:
    return np.sqrt(x)
f_vec = np.vectorize(f)
f_vec(10)==f(10)

True

In [16]:
# Factorial
special.factorial(5)

120.0

In [17]:
# n-th derivative of a function at a point
def continuousFunc(x):
  return 3*(x**2)
misc.derivative(continuousFunc, 5)

30.0